### PR TITLE
Allow calling on underscore's reduce on children views

### PR DESCRIPTION
**Pull request by romanbsd**

### CODE REVIEW

**Comment by samccone** [comment]
We will want to update the docs here as well
https://github.com/marionettejs/backbone.babysitter#iterators-and-collection-functions

**Comment by romanbsd** [comment]
Good point. I updated the readme.

**Comment by samccone** [comment]
:clap: great work thanks so much @romanbsd I will do a release of this today

**Comment by samccone** [comment]
Fixes #53

**Comment by samccone** [comment]
merged! and released under 0.1.6

**Pull request closed without merging**
