### PR TITLE
Move add and remove view logic to another function in order to control when to use _updateLength

### LINKED ISSUE #66: Update for lodash v4
XRef: https://github.com/marionettejs/backbone.marionette/pull/2889

A few methods using context.
`_.tail` an issue?
One `_.any`

Might be others.

### PR DESCRIPTION
**Pull request by rafde**
This will help with marionettejs/backbone.marionette#2873
This change will help when adding a large number of views by using _add then later using _updateLength after all the views are done getting added. Same use case for _remove.

Old PR #67 
Closes #66

### CODE REVIEW

**Comment by JSteunou** [comment]
I see 3 changes with a lot of noises around

1. 2 bind added (is this for lodash?)
2. _.tail replaced by toArray slice(1)
3. any replace by some (this one bothers me)

@rafde if I understand what you're trying to achieve, this PR is an pre-requisite for another PR?

Could it be separate into 3 PR? one for lodash issue, one for typo and cleaning, and one for the real goal.

**Comment by rafde** [comment]
@jsteunou If I see 2 team members 👍your comment, I'll update the pr. I need to make sure I am using my time wisely, considering how long it's taken to get a response. Also to see if I should move forward resolving the performance issues in marionette collection view

**Comment by paulfalgout** [comment]
I'd merge the lodash issues (including replacing some for any) and the cleaning super quick.  I don't have strong opinions on the main goal.  Was hoping more @marionettejs/marionette-core would speak into that.

**Comment by rafde** [comment]
So separate PR for
> I'd merge the lodash issues (including replacing some for any) and the cleaning super quick.
?
Or keep here?

**Comment by ahumphreys87** [comment]
@radfe I think keep in this PR but split into separate commits if you don't mind?

As for the real goal, I'm really interested in seeing the CollectionView perf changes you have in mind. If you can get this split up we can get this merged quickly

**Comment by rafde** [comment]
@ahumphreys87 @paulfalgout done

**Comment by rafde** [comment]
Did one more commit for granularity

**Comment by samccone** [comment]
:+1:

**Comment by rafde** [comment]
C'mon, big :moneybag:. One more approval and we can get the ball rolling on collectionView perf updates.

**Comment by ahumphreys87** [comment]
:+1:

**Comment by ahumphreys87** [comment]
:dancer:

**Comment by rafde** [comment]
🎉 👯 🎆

**Pull request merged**
